version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'kbrashears5'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'kbrashears5'
    groups:
      all:
        patterns:
          - '*'