version: 2
updates:
  ### update dependencies daily
  # package.json in root directory
  - package-ecosystem: 'npm'
    directory: '/'
    # daily at 5am UTC
    schedule:
      interval: 'weekly'
    # always get latest version
    versioning-strategy: increase
    # set reviewers
    reviewers:
      - 'kbrashears5'
