name: Repository Issue Assigner

on:
  issues:
    types: [opened]

jobs:
  issue_assigner:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Notifier
        uses: kbrashears5/github-action-issue-assigner@master
        with:
          TOKEN: ${{ secrets.BOT_ACTIONS }}
