name: Repo Metadata Sync

on:
  push:
    branches:
      - master

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Repo Sync
        uses: kbrashears5/github-action-repo-sync@master
        with:
          TYPE: npm
          PATH: package.json
          TOKEN: ${{ secrets.ACTIONS }}
